FROM rwthika/ros2-ml@sha256:1c24b67c934aeb6dff7d7eb7a81fa5a438bf3e5ec4f1433f065b644d75c190f5 AS builder-base

# S
ENV ROS_DISTRO=humble
ARG CR_PAT
ARG DEBIAN_FRONTEND=noninteractive
ENV OMNI_KIT_ACCEPT_EULA=YES
ENV NVIDIA_VISIBLE_DEVICES=all
ENV NVIDIA_DRIVER_CAPABILITIES=all
ARG ISAAC_VERSION

# Install IsaacSim
COPY requirements/isaac_requirements_${ISAAC_VERSION}.txt tmp/isaac_requirements.txt
RUN --mount=type=cache,target=/var/cache/apt \
    --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r tmp/isaac_requirements.txt

COPY requirements/ros_requirements.txt tmp/ros_requirements.txt
RUN --mount=type=cache,target=/root/.cache/pip \
    pip3 install -r tmp/ros_requirements.txt
